spring:
  application:
    name: mailservice
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

app:
  mail:
    from: noreply@gmail.com
    from-name: Second Life
    base-url: http://localhost:8080

logging:
  file:
    name: mailservice.log
  logback:
    rollingpolicy:
      file-name-pattern: mailservice-%d{yyyy-MM-dd}.log
      max-file-size: 10MB
  level:
    com.naodab.mailservice: DEBUG
    org.springframework.kafka: INFO
