services:
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    restart: unless-stopped
    ports:
      - 9092:9092
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 45s
    networks:
      - second_life_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: second-life
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - second_life_network

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - second_life_network
    volumes:
      - redis-data:/data

  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "9080:8080"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml
    networks:
      - second_life_network

  auth-service:
    image: auth-service:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: authservice/Dockerfile
    ports:
      - "${SERVER_PORT_AUTH_SERVICE}:${SERVER_PORT_AUTH_SERVICE}"
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
      # - db
    networks:
      - second_life_network
    labels:
      - "traefik.enable=true"

  mail-service:
    image: mail-service:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: mailservice/Dockerfile
    ports:
      - "${SERVER_PORT_MAIL_SERVICE}:${SERVER_PORT_MAIL_SERVICE}"
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - second_life_network
    labels:
      - "traefik.enable=true"

  profile-service:
    image: profile-service:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: profileservice/Dockerfile
    ports:
      - "${SERVER_PORT_PROFILE_SERVICE}:${SERVER_PORT_PROFILE_SERVICE}"
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
      # - db
    networks:
      - second_life_network
    labels:
      - "traefik.enable=true"

  upload-service:
    image: upload-service:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: uploadservice/Dockerfile
    ports:
      - "${SERVER_PORT_UPLOAD_SERVICE}:${SERVER_PORT_UPLOAD_SERVICE}"
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - second_life_network
    labels:
      - "traefik.enable=true"

  location-service:
    image: location-service:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: locationservice/Dockerfile
    ports:
      - "${SERVER_PORT_LOCATION_SERVICE}:${SERVER_PORT_LOCATION_SERVICE}"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
    networks:
      - second_life_network
    labels:
      - "traefik.enable=true"

volumes:
  kafka-data:
  mysql-data:
  redis-data:

networks:
  second_life_network:
    driver: bridge
