services:
  traefik:
    ports:
      - "9080:8080"
    volumes:
      - ./traefik/traefik.dev.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml

  # auth-service:
  #   environment:
  #     SPRING_PROFILES_ACTIVE: dev
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./pom.xml
  #         ignore:
  #           - "**/target/**"
  #       - action: rebuild
  #         path: ./commonjpa
  #         ignore:
  #           - "**/target/**"
  #       - action: rebuild
  #         path: ./commonservice
  #         ignore:
  #           - "**/target/**"
  #       - action: rebuild
  #         path: ./authservice
  #         ignore:
  #           - "**/target/**"

  # mail-service:
  #   environment:
  #     SPRING_PROFILES_ACTIVE: dev
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./pom.xml
  #         ignore:
  #           - "**/target/**"
  #       - action: rebuild
  #         path: ./commonjpa
  #         ignore:
  #           - "**/target/**"
  #       - action: rebuild
  #         path: ./commonservice
  #         ignore:
  #           - "**/target/**"
  #       - action: rebuild
  #         path: ./mailservice
  #         ignore:
  #           - "**/target/**"

  # profile-service:
  #   environment:
  #     SPRING_PROFILES_ACTIVE: dev
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./pom.xml
  #         ignore:
  #           - "**/target/**"
  #       - action: rebuild
  #         path: ./commonjpa
  #         ignore:
  #           - "**/target/**"
  #       - action: rebuild
  #         path: ./commonservice
  #         ignore:
  #           - "**/target/**"
  #       - action: rebuild
  #         path: ./profileservice
  #         ignore:
  #           - "**/target/**"

  # location-service:
  #   environment:
  #     SPRING_PROFILES_ACTIVE: dev
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./pom.xml
  #         ignore:
  #           - "**/target/**"
  #       - action: rebuild
  #         path: ./commonservice
  #         ignore:
  #           - "**/target/**"
  #       - action: rebuild
  #         path: ./locationservice
  #         ignore:
  #           - "**/target/**"

  ai-service:
    develop:
      watch:
        - action: rebuild
          path: ./aiservice/requirements.txt
        - action: rebuild
          path: ./aiservice/wsgi.py
        - action: rebuild
          path: ./aiservice/app
          ignore:
            - "**/__pycache__/**"
            - "**/*.pyc"

  product-service:
    environment:
      SPRING_PROFILES_ACTIVE: dev
      AI_SERVICE_URL: http://ai-service:8090
    develop:
      watch:
        - action: rebuild
          path: ./pom.xml
          ignore:
            - "**/target/**"
        - action: rebuild
          path: ./commonjpa
          ignore:
            - "**/target/**"
        - action: rebuild
          path: ./commonservice
          ignore:
            - "**/target/**"
        - action: rebuild
          path: ./productservice
          ignore:
            - "**/target/**"

  # inventory-service:
  #   environment:
  #     SPRING_PROFILES_ACTIVE: dev
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./pom.xml
  #         ignore:
  #           - "**/target/**"
  #       - action: rebuild
  #         path: ./commonservice
  #         ignore:
  #           - "**/target/**"
  #       - action: rebuild
  #         path: ./inventoryservice
  #         ignore:
  #           - "**/target/**"

  # booking-service:
  #   environment:
  #     SPRING_PROFILES_ACTIVE: dev
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./pom.xml
  #         ignore:
  #           - "**/target/**"
  #       - action: rebuild
  #         path: ./commonservice
  #         ignore:
  #           - "**/target/**"
  #       - action: rebuild
  #         path: ./bookingservice
  #         ignore:
  #           - "**/target/**"
  #       - action: rebuild
  #         path: ./inventoryservice
  #         ignore:
  #           - "**/target/**"
