http:
  middlewares:
    gateway-jwt:
      forwardAuth:
        address: "http://auth-service:8081/api/v1/auth/forward-auth"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Profile-Id"
          - "X-User-Email"
          - "role"
        authRequestHeaders:
          - "Authorization"

  routers:
    auth-api:
      rule: "PathPrefix(`/api/v1/auth`) || PathPrefix(`/api/v1/oauth2`) || PathPrefix(`/api/v1/login/oauth2`) || PathPrefix(`/oauth2`) || PathPrefix(`/login/oauth2`)"
      service: auth-service
      entryPoints:
        - web
    profile-api-options:
      rule: "PathPrefix(`/api/v1/profiles`) && Method(`OPTIONS`)"
      service: profile-service
      entryPoints:
        - web
      priority: 100
    profile-api:
      rule: "PathPrefix(`/api/v1/profiles`)"
      service: profile-service
      entryPoints:
        - web
      middlewares:
        - gateway-jwt
      priority: 1
    mail-api-options:
      rule: "PathPrefix(`/api/test`) && Method(`OPTIONS`)"
      service: mail-service
      entryPoints:
        - web
      priority: 100
    mail-api:
      rule: "PathPrefix(`/api/test`)"
      service: mail-service
      entryPoints:
        - web
      middlewares:
        - gateway-jwt
      priority: 1
    location-api-options:
      rule: "PathPrefix(`/api/v1/provinces`) || PathPrefix(`/api/v1/wards`) && Method(`OPTIONS`)"
      service: location-service
      entryPoints:
        - web
      priority: 100
    location-api:
      rule: "PathPrefix(`/api/v1/provinces`) || PathPrefix(`/api/v1/wards`)"
      service: location-service
      entryPoints:
        - web
      priority: 1
    product-api-options:
      rule: "(PathPrefix(`/api/v1/facilities`) || PathPrefix(`/api/v1/categories`) || PathPrefix(`/api/v1/sub-categories`) || PathPrefix(`/api/v1/attributes`) || PathPrefix(`/api/v1/products`)) && Method(`OPTIONS`)"
      service: product-service
      entryPoints:
        - web
      priority: 100
    product-api:
      rule: "PathPrefix(`/api/v1/facilities`) || PathPrefix(`/api/v1/categories`) || PathPrefix(`/api/v1/sub-categories`) || PathPrefix(`/api/v1/attributes`) || PathPrefix(`/api/v1/products`)"
      service: product-service
      entryPoints:
        - web
      middlewares:
        - gateway-jwt
      priority: 1

  services:
    auth-service:
      loadBalancer:
        servers:
          - url: "http://auth-service:8081"
    profile-service:
      loadBalancer:
        servers:
          - url: "http://profile-service:8082"
    mail-service:
      loadBalancer:
        servers:
          - url: "http://mail-service:8083"
    location-service:
      loadBalancer:
        servers:
          - url: "http://location-service:8085"
    product-service:
      loadBalancer:
        servers:
          - url: "http://product-service:8086"
