spring:
  application:
    name: authservice
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USENAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
  jackson:
    serialization:
      "[indent_output]": true
    deserialization:
      fail-on-unknown-properties: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIEN_SECRET}
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:authservice-consumer}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      properties:
        "[spring.json.trusted.packages]": "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topics:
      email-verification: "mail.email-verification"
      forgot-password: "mail.forgot-password"

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration: 86400000
    refresh-expiration: 604800000
  oauth2:
    authorized-redirect-uris:
      - http://localhost:3000/oauth2/redirect
      - http://localhost:8080/oauth2/redirect
      - http://localhost:5500/test_login_google.html
  verification-token-expiration: 180000
  forgot-password-token-expiration: 60000

external:
  frontend_url: http://localhost:8080

logging:
  level:
    "[com.example.authservice]": DEBUG
    "[org.springframework.security]": DEBUG
